### PR TITLE
add HDTOptions parameter in the HDTManager mapIndexedHDT and load methods

### PR DESCRIPTION
**Pull request by ate47**
In this PR, I've added a parameter to specify a HDTOptions when we are indexing a HDT with the HDTManager class.

### CODE REVIEW

**Comment by D063520** [comment]
@mielvds : hi, I'm in favour of this pull request. It basically allows to specify the HDT specifications (HDTOptions) when mapping an HDT file. This does not change current APIs. It only adds functionality.

@ate47 : to be symmetric, should not also the same be done for the loadHDT methods?

**Comment by ate47** [comment]
> the same be done for the loadHDT methods

I wasn't thinking about that, good idea.

**Comment by D063520** [comment]
I was checking quickly, it is important that all previews existing methods still exist. We should only add new constructors, not remove old ones. Is this the case?

**Comment by D063520** [comment]
After checking more carefully, I'm in favour of this pull request. It is important because for new variations of HDT we need to be able to pass the correct spec.

**Comment by mielvds** [comment]
Hi all, 

Fine by me, but there should be no change in the existing abstract methods of `HDTManager`. Just overload them.

**Comment by ate47** [comment]
> Can't you overload them instead?

Something like this where we have the 2 versions?

```java
protected abstract HDT doLoadHDT(String hdtFileName, ProgressListener listener) throws IOException;
protected abstract HDT doLoadHDT(String hdtFileName, ProgressListener listener, HDTOptions spec) throws IOException;
```

Wouldn't it be better to have only one version to implement? Because we need to add a new method or a new parameter for each load, so the implementation would be changed in both cases.

**Comment by mielvds** [comment]
You might break somebody's code.  You implement them as non-abstract that call the other one. 

And shouldn't it be 
```
	public static HDT loadHDT(String hdtFileName, ProgressListener listener) throws IOException {
		return HDTManager.getInstance().doLoadHDT(hdtFileName, listener, new HDTSpecification());
	}
```
Instead of 

```
	public static HDT loadHDT(String hdtFileName, ProgressListener listener) throws IOException {
		return HDTManager.getInstance().doLoadHDT(hdtFileName, listener, null);
	}
```

**Comment by ate47** [comment]
> You might break somebody's code. You could implement them as non-abstract and call the other one.

In this PR, I'm adding new methods in the API usage, but it requires to reflect them on a CORE implementation, so it might break somebody's code of an implementation of the API, not on the usage of the API. So I don't understand how you want me to pass it without touching how the API should be implemented.

**Comment by ate47** [comment]
> And shouldn't it be [...] Instead of [...]

Because [``HDTSpecification``](https://github.com/rdfhdt/hdt-java/blob/master/hdt-java-core/src/main/java/org/rdfhdt/hdt/options/HDTSpecification.java) is a CORE class and not an API class, I can't use it in the API, I've used *null* as a default value and in [``HDTImpl#155``](https://github.com/ate47/hdt-java/blob/3.0.0/hdt-java-core/src/main/java/org/rdfhdt/hdt/hdt/impl/HDTImpl.java#L155), I'm setting the default value. 

Another way would have been to add a new method in ``HDTManager`` or another API class to create a default HDTOptions, but it would requires to add a new method to implement, like in my previous message.

**Comment by ate47** [comment]
In the Javadoc of each methods, I've added:

> Can be null for default options.

To express the null for implementation.

**Comment by mielvds** [comment]
@ate47 fair enough! Could you fix the conflicts? I'll merge after

**Comment by mielvds** [comment]
@ate47 the tests were failing, so I reverted the PR. Can you check https://github.com/rdfhdt/hdt-java/runs/5230092243?check_suite_focus=true

**Comment by ate47** [comment]
Yes, I was working on that when you merged the PR.

**Comment by mielvds** [comment]
whops, sorry, thought you were done :)

**Pull request merged**
