### PR TITLE
Apache jena upgrade

### PR DESCRIPTION
**Pull request by JervenBolleman**
This upgrade to Apache-Jena 3.17.0 and changes the hdt-fuseki to be based on fuseki2. Query service works but nothing else has been tested or looked at yet. Just wanted to let people know that this exists for further work.

### CODE REVIEW

**Comment by JervenBolleman** [comment]
Once #119 is merged, I will rebase this pull request.

**Comment by mielvds** [comment]
@JervenBolleman you can rebase now. But didn't #119 already upgrade the jena version?

**Comment by mielvds** [comment]
In another note: would it be much work to include https://github.com/rdfhdt/hdt-java/issues/3?

**Comment by JervenBolleman** [comment]
@mielvds this also upgrades the Jena Fuseki part. #119 only upgraded jena for the core part. I will need some time to look at it again as the rebase is not trivial. I will try to have a look at #3 as well. But not until end of May 2021.

**Comment by mielvds** [comment]
@JervenBolleman, not sure if you're still interested, but I'm grouping this to the move to Jena 4.3.2

**Pull request merged**
