### PR TITLE
fix: remove spurious system.out.println from api triples/tripleID:equ…

### PR DESCRIPTION
**Pull request by ericprud**
I'm guessing this was left over from some diagnostics.I don't know if this code is ever called.

### CODE REVIEW

**Comment by afs** [comment]
The `equals(TripleId)` method can be deleted; there is an implementation of `equals(Object)` lower down.

Ideally, `equals(Object)` should return false for the corner case of `o` being null.

**Comment by ericprud** [comment]
> The `equals(TripleId)` method can be deleted; there is an implementation of `equals(Object)` lower down.

I'm not man enough to go deleting methods.


> Ideally, `equals(Object)` should return false for the corner case of `o` being null.

In this case, should null == null?

**Comment by afs** [comment]
`equals` is an object method so `this` can't be null.

**Comment by mielvds** [comment]
@afs is right, so you have my blessing to delete @ericprud  :)
An alternative is to call `equals(TripleId)` in `equals(Object)`;

**Comment by ericprud** [comment]
I've updated the PR but I want to be sure that I've tested it. I assumed that @afs was saying that `equals(TripleID other)` redundant against a more general `equals(Object o)` function. Given that, I thought that I'd screw things up by changing removing the `!` on the return:
``` java
public boolean equals(TripleID other) {
	return ( subject!=other.subject || predicate!=other.predicate || object!=other.object );
}
```
Running  the tests showed no errors:
``` shell
eric@touchy:/tmp/checkouts/ericprud/hdt-java$ mvn test 2>/dev/null | grep Tests\ run:
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.055 sec
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.122 sec
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.054 sec
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.073 sec
Tests run: 52, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.836 sec
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.315 sec
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.01 sec
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.374 sec
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec
Tests run: 35, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.037 sec
Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.304 sec
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 sec
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Tests run: 147, Failures: 0, Errors: 0, Skipped: 0
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.443 sec
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.347 sec
Tests run: 529, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.701 sec
Tests run: 268, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.736 sec
Tests run: 19, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.032 sec
Tests run: 17, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.022 sec
Tests run: 18, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.031 sec
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 sec
Tests run: 860, Failures: 0, Errors: 0, Skipped: 0
```

The same change applied to `public boolean equals(Object o)` did break things:
```
Tests run: 10, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 1.353 sec <<< FAILURE!
...
Tests run: 147, Failures: 2, Errors: 0, Skipped: 0
```
so I probably just misinterpreted the inheritance. Regardless, mvn ended with all green, which could really lead one down a garden path.

> @afs is right, so you have my blessing to delete @ericprud :)

(or maybe you want me to "delete @ericprud", which would lead to existential crisis)

**Comment by afs** [comment]
`rm -f @ericprud`.

Here is code generated by Eclipse to do "equals" and "hashCode" for a class of 3 longs: it shows how to check for nulls before accessing the field of `other`.

```java
    class Demo {
        long subject;
        long predicate;
        long object;

        @Override
        public int hashCode() {
            return Objects.hash(object, predicate, subject);
        }

        @Override
        public boolean equals(Object obj) {
            if ( this == obj )
                return true;
            if ( obj == null )
                return false;
            if ( getClass() != obj.getClass() )
                return false;
            Demo other = (Demo)obj;
            return object == other.object && predicate == other.predicate && subject == other.subject;
        }
    }
```

**Comment by ericprud** [comment]
> `rm -f @ericprud`.

rm -**r**f (don't forget my kid or you'll get some sort of error)

> if ( obj == null )...

Does Intellij or something else do this sort of analysis on existing code.

**Comment by afs** [comment]
> Does Intellij or something else do this sort of analysis on existing code.

I don' t use IntelliJ but the documentation ... https://www.jetbrains.com/help/idea/generating-code.html#generate-getters-setters

**Comment by mielvds** [comment]
How should we proceed?

**Review by afs — APPROVED** [review]

**Comment by afs** [comment]
LGTM. Apply the patch.

**Pull request merged**
